STOCK_TO_SECTOR = {
    "360ONE": "Financial Services",
    "3MINDIA": "Diversified",
    "AADHARHFC": "Financial Services",
    "AARTIDRUGS": "Healthcare",
    "AARTIIND": "Chemicals",
    "AARTIPHARM": "Healthcare",
    "AAVAS": "Financial Services",
    "ABB": "Capital Goods",
    "ABBOTINDIA": "Healthcare",
    "ABCAPITAL": "Financial Services",
    "ABDL": "Fast Moving Consumer Goods",
    "ABFRL": "Consumer Services",
    "ABLBL": "Consumer Services",
    "ABREL": "Forest Materials",
    "ABSLAMC": "Financial Services",
    "ACC": "Construction Materials",
    "ACE": "Capital Goods",
    "ACI": "Chemicals",
    "ACMESOLAR": "Power",
    "ACUTAAS": "Healthcare",
    "ADANIENSOL": "Power",
    "ADANIENT": "Metals & Mining",
    "ADANIGREEN": "Power",
    "ADANIPORTS": "Services",
    "ADANIPOWER": "Power",
    "ADVENTHTL": "Consumer Services",
    "ADVENZYMES": "Healthcare",
    "AEGISLOG": "Oil, Gas & Consumable Fuels",
    "AEGISVOPAK": "Oil, Gas & Consumable Fuels",
    "AETHER": "Chemicals",
    "AFCONS": "Construction",
    "AFFLE": "Information Technology",
    "AGARWALEYE": "Healthcare",
    "AGI": "Capital Goods",
    "AHLUCONT": "Construction",
    "AIAENG": "Capital Goods",
    "AIIL": "Financial Services",
    "AJANTPHARM": "Healthcare",
    "AJAXENGG": "Capital Goods",
    "AKUMS": "Healthcare",
    "AKZOINDIA": "Consumer Durables",
    "ALIVUS": "Healthcare",
    "ALKEM": "Healthcare",
    "ALKYLAMINE": "Chemicals",
    "ALLCARGO": "Services",
    "ALOKINDS": "Textiles",
    "AMBER": "Consumer Durables",
    "AMBUJACEM": "Construction Materials",
    "ANANDRATHI": "Financial Services",
    "ANANTRAJ": "Realty",
    "ANGELONE": "Financial Services",
    "ANUP": "Capital Goods",
    "ANURAS": "Chemicals",
    "APARINDS": "Capital Goods",
    "APLAPOLLO": "Capital Goods",
    "APLLTD": "Healthcare",
    "APOLLOHOSP": "Healthcare",
    "APOLLOTYRE": "Automobile and Auto Components",
    "APTUS": "Financial Services",
    "ARE&M": "Automobile and Auto Components",
    "ARVIND": "Textiles",
    "ARVINDFASN": "Consumer Services",
    "ASAHIINDIA": "Automobile and Auto Components",
    "ASHOKA": "Construction",
    "ASHOKLEY": "Capital Goods",
    "ASIANPAINT": "Consumer Durables",
    "ASKAUTOLTD": "Automobile and Auto Components",
    "ASTERDM": "Healthcare",
    "ASTRAL": "Capital Goods",
    "ASTRAMICRO": "Capital Goods",
    "ASTRAZEN": "Healthcare",
    "ATGL": "Oil, Gas & Consumable Fuels",
    "ATHERENERG": "Automobile and Auto Components",
    "ATUL": "Chemicals",
    "AUBANK": "Financial Services",
    "AURIONPRO": "Information Technology",
    "AUROPHARMA": "Healthcare",
    "AVALON": "Capital Goods",
    "AVANTIFEED": "Fast Moving Consumer Goods",
    "AWFIS": "Services",
    "AWL": "Fast Moving Consumer Goods",
    "AXISBANK": "Financial Services",
    "AZAD": "Capital Goods",
    "BAJAJ-AUTO": "Automobile and Auto Components",
    "BAJAJELEC": "Consumer Durables",
    "BAJAJFINSV": "Financial Services",
    "BAJAJHFL": "Financial Services",
    "BAJAJHLDNG": "Financial Services",
    "BAJFINANCE": "Financial Services",
    "BALAMINES": "Chemicals",
    "BALKRISIND": "Automobile and Auto Components",
    "BALRAMCHIN": "Fast Moving Consumer Goods",
    "BALUFORGE": "Capital Goods",
    "BANCOINDIA": "Automobile and Auto Components",
    "BANDHANBNK": "Financial Services",
    "BANKBARODA": "Financial Services",
    "BANKINDIA": "Financial Services",
    "BASF": "Chemicals",
    "BATAINDIA": "Consumer Durables",
    "BAYERCROP": "Chemicals",
    "BBL": "Capital Goods",
    "BBTC": "Fast Moving Consumer Goods",
    "BDL": "Capital Goods",
    "BECTORFOOD": "Fast Moving Consumer Goods",
    "BEL": "Capital Goods",
    "BELRISE": "Automobile and Auto Components",
    "BEML": "Capital Goods",
    "BERGEPAINT": "Consumer Durables",
    "BHARATFORG": "Automobile and Auto Components",
    "BHARTIARTL": "Telecommunication",
    "BHARTIHEXA": "Telecommunication",
    "BHEL": "Capital Goods",
    "BIKAJI": "Fast Moving Consumer Goods",
    "BIOCON": "Healthcare",
    "BIRLACORPN": "Construction Materials",
    "BLACKBUCK": "Services",
    "BLS": "Consumer Services",
    "BLUEDART": "Services",
    "BLUEJET": "Healthcare",
    "BLUESTARCO": "Consumer Durables",
    "BORORENEW": "Capital Goods",
    "BOSCHLTD": "Automobile and Auto Components",
    "BPCL": "Oil, Gas & Consumable Fuels",
    "BRIGADE": "Realty",
    "BRITANNIA": "Fast Moving Consumer Goods",
    "BSE": "Financial Services",
    "BSOFT": "Information Technology",
    "CAMPUS": "Consumer Durables",
    "CAMS": "Financial Services",
    "CANBK": "Financial Services",
    "CANFINHOME": "Financial Services",
    "CAPLIPOINT": "Healthcare",
    "CARBORUNIV": "Capital Goods",
    "CARTRADE": "Consumer Services",
    "CASTROLIND": "Oil, Gas & Consumable Fuels",
    "CCL": "Fast Moving Consumer Goods",
    "CDSL": "Financial Services",
    "CEATLTD": "Automobile and Auto Components",
    "CEIGALL": "Construction",
    "CELLO": "Consumer Durables",
    "CEMPRO": "Construction",
    "CENTRALBK": "Financial Services",
    "CENTURYPLY": "Consumer Durables",
    "CERA": "Consumer Durables",
    "CESC": "Power",
    "CGCL": "Financial Services",
    "CGPOWER": "Capital Goods",
    "CHALET": "Consumer Services",
    "CHAMBLFERT": "Chemicals",
    "CHENNPETRO": "Oil, Gas & Consumable Fuels",
    "CHOICEIN": "Financial Services",
    "CHOLAFIN": "Financial Services",
    "CHOLAHLDNG": "Financial Services",
    "CIEINDIA": "Automobile and Auto Components",
    "CIGNITITEC": "Information Technology",
    "CIPLA": "Healthcare",
    "CLEAN": "Chemicals",
    "CMSINFO": "Services",
    "COALINDIA": "Oil, Gas & Consumable Fuels",
    "COCHINSHIP": "Capital Goods",
    "COFORGE": "Information Technology",
    "COHANCE": "Healthcare",
    "COLPAL": "Fast Moving Consumer Goods",
    "CONCOR": "Services",
    "CONCORDBIO": "Healthcare",
    "COROMANDEL": "Chemicals",
    "CRAFTSMAN": "Automobile and Auto Components",
    "CREDITACC": "Financial Services",
    "CRISIL": "Financial Services",
    "CROMPTON": "Consumer Durables",
    "CSBBANK": "Financial Services",
    "CUB": "Financial Services",
    "CUMMINSIND": "Capital Goods",
    "CYIENT": "Information Technology",
    "CYIENTDLM": "Capital Goods",
    "DABUR": "Fast Moving Consumer Goods",
    "DALBHARAT": "Construction Materials",
    "DATAMATICS": "Information Technology",
    "DATAPATTNS": "Capital Goods",
    "DBL": "Construction",
    "DBREALTY": "Consumer Services",
    "DCAL": "Healthcare",
    "DCBBANK": "Financial Services",
    "DCMSHRIRAM": "Diversified",
    "DEEPAKFERT": "Chemicals",
    "DEEPAKNTR": "Chemicals",
    "DELHIVERY": "Services",
    "DEVYANI": "Consumer Services",
    "DHANUKA": "Chemicals",
    "DIACABS": "Capital Goods",
    "DIVISLAB": "Healthcare",
    "DIXON": "Consumer Durables",
    "DLF": "Realty",
    "DMART": "Consumer Services",
    "DODLA": "Fast Moving Consumer Goods",
    "DOMS": "Fast Moving Consumer Goods",
    "DRREDDY": "Healthcare",
    "DYNAMATECH": "Capital Goods",
    "EASEMYTRIP": "Consumer Services",
    "ECLERX": "Services",
    "EDELWEISS": "Financial Services",
    "EICHERMOT": "Automobile and Auto Components",
    "EIDPARRY": "Fast Moving Consumer Goods",
    "EIEL": "Utilities",
    "EIHOTEL": "Consumer Services",
    "ELECON": "Capital Goods",
    "ELECTCAST": "Capital Goods",
    "ELGIEQUIP": "Capital Goods",
    "EMAMILTD": "Fast Moving Consumer Goods",
    "EMBDL": "Realty",
    "EMCURE": "Healthcare",
    "EMIL": "Consumer Services",
    "EMUDHRA": "Information Technology",
    "ENDURANCE": "Automobile and Auto Components",
    "ENGINERSIN": "Construction",
    "ENRIN": "Capital Goods",
    "ENTERO": "Consumer Services",
    "EPIGRAL": "Chemicals",
    "EPL": "Capital Goods",
    "EQUITASBNK": "Financial Services",
    "ERIS": "Healthcare",
    "ESCORTS": "Capital Goods",
    "ETERNAL": "Consumer Services",
    "ETHOSLTD": "Consumer Durables",
    "EUREKAFORB": "Consumer Durables",
    "EXIDEIND": "Automobile and Auto Components",
    "FACT": "Chemicals",
    "FDC": "Healthcare",
    "FEDERALBNK": "Financial Services",
    "FIEMIND": "Automobile and Auto Components",
    "FINCABLES": "Capital Goods",
    "FINEORG": "Chemicals",
    "FINPIPE": "Capital Goods",
    "FIRSTCRY": "Consumer Services",
    "FIVESTAR": "Financial Services",
    "FLUOROCHEM": "Chemicals",
    "FORCEMOT": "Automobile and Auto Components",
    "FORTIS": "Healthcare",
    "FSL": "Services",
    "GABRIEL": "Automobile and Auto Components",
    "GAEL": "Fast Moving Consumer Goods",
    "GAIL": "Oil, Gas & Consumable Fuels",
    "GALLANTT": "Capital Goods",
    "GANECOS": "Textiles",
    "GANESHHOU": "Realty",
    "GARFIBRES": "Textiles",
    "GATEWAY": "Services",
    "GESHIP": "Services",
    "GHCL": "Chemicals",
    "GICRE": "Financial Services",
    "GILLETTE": "Fast Moving Consumer Goods",
    "GLAND": "Healthcare",
    "GLAXO": "Healthcare",
    "GLENMARK": "Healthcare",
    "GMDCLTD": "Metals & Mining",
    "GMMPFAUDLR": "Capital Goods",
    "GMRAIRPORT": "Services",
    "GMRP&UI": "Power",
    "GNFC": "Chemicals",
    "GODFRYPHLP": "Fast Moving Consumer Goods",
    "GODIGIT": "Financial Services",
    "GODREJAGRO": "Fast Moving Consumer Goods",
    "GODREJCP": "Fast Moving Consumer Goods",
    "GODREJIND": "Diversified",
    "GODREJPROP": "Realty",
    "GOKEX": "Textiles",
    "GPIL": "Capital Goods",
    "GPPL": "Services",
    "GRANULES": "Healthcare",
    "GRAPHITE": "Capital Goods",
    "GRASIM": "Construction Materials",
    "GRAVITA": "Metals & Mining",
    "GREAVESCOT": "Capital Goods",
    "GREENPANEL": "Consumer Durables",
    "GRINFRA": "Construction",
    "GRSE": "Capital Goods",
    "GRWRHITECH": "Capital Goods",
    "GSFC": "Chemicals",
    "GSPL": "Oil, Gas & Consumable Fuels",
    "GUJGASLTD": "Oil, Gas & Consumable Fuels",
    "GULFOILLUB": "Oil, Gas & Consumable Fuels",
    "GVT&D": "Capital Goods",
    "HAL": "Capital Goods",
    "HAPPSTMNDS": "Information Technology",
    "HAVELLS": "Consumer Durables",
    "HBLENGINE": "Capital Goods",
    "HCC": "Construction",
    "HCG": "Healthcare",
    "HCLTECH": "Information Technology",
    "HDFCAMC": "Financial Services",
    "HDFCBANK": "Financial Services",
    "HDFCLIFE": "Financial Services",
    "HEG": "Capital Goods",
    "HEMIPROP": "Services",
    "HERITGFOOD": "Fast Moving Consumer Goods",
    "HEROMOTOCO": "Automobile and Auto Components",
    "HEXT": "Information Technology",
    "HFCL": "Telecommunication",
    "HGINFRA": "Construction",
    "HIKAL": "Healthcare",
    "HINDALCO": "Metals & Mining",
    "HINDCOPPER": "Metals & Mining",
    "HINDPETRO": "Oil, Gas & Consumable Fuels",
    "HINDUNILVR": "Fast Moving Consumer Goods",
    "HINDZINC": "Metals & Mining",
    "HOMEFIRST": "Financial Services",
    "HONASA": "Fast Moving Consumer Goods",
    "HONAUT": "Capital Goods",
    "HSCL": "Chemicals",
    "HUDCO": "Financial Services",
    "HYUNDAI": "Automobile and Auto Components",
    "ICICIBANK": "Financial Services",
    "ICICIGI": "Financial Services",
    "ICICIPRULI": "Financial Services",
    "ICIL": "Textiles",
    "IDBI": "Financial Services",
    "IDEA": "Telecommunication",
    "IDFCFIRSTB": "Financial Services",
    "IEX": "Financial Services",
    "IFBIND": "Consumer Durables",
    "IFCI": "Financial Services",
    "IGIL": "Services",
    "IGL": "Oil, Gas & Consumable Fuels",
    "IIFL": "Financial Services",
    "IIFLCAPS": "Financial Services",
    "IKS": "Information Technology",
    "IMAGICAA": "Consumer Services",
    "IMFA": "Metals & Mining",
    "INDGN": "Healthcare",
    "INDHOTEL": "Consumer Services",
    "INDIACEM": "Construction Materials",
    "INDIAGLYCO": "Fast Moving Consumer Goods",
    "INDIAMART": "Consumer Services",
    "INDIANB": "Financial Services",
    "INDIASHLTR": "Financial Services",
    "INDIGO": "Services",
    "INDIGOPNTS": "Consumer Durables",
    "INDUSINDBK": "Financial Services",
    "INDUSTOWER": "Telecommunication",
    "INFY": "Information Technology",
    "INGERRAND": "Capital Goods",
    "INNOVACAP": "Healthcare",
    "INOXGREEN": "Power",
    "INOXINDIA": "Capital Goods",
    "INOXWIND": "Capital Goods",
    "INTELLECT": "Information Technology",
    "IOB": "Financial Services",
    "IOC": "Oil, Gas & Consumable Fuels",
    "IONEXCHANG": "Utilities",
    "IPCALAB": "Healthcare",
    "IRB": "Construction",
    "IRCON": "Construction",
    "IRCTC": "Consumer Services",
    "IREDA": "Financial Services",
    "IRFC": "Financial Services",
    "ISGEC": "Construction",
    "ITC": "Fast Moving Consumer Goods",
    "ITCHOTELS": "Consumer Services",
    "ITI": "Telecommunication",
    "IXIGO": "Consumer Services",
    "J&KBANK": "Financial Services",
    "JAIBALAJI": "Metals & Mining",
    "JAMNAAUTO": "Automobile and Auto Components",
    "JBCHEPHARM": "Healthcare",
    "JBMA": "Automobile and Auto Components",
    "JINDALSAW": "Capital Goods",
    "JINDALSTEL": "Metals & Mining",
    "JINDWORLD": "Textiles",
    "JIOFIN": "Financial Services",
    "JISLJALEQS": "Capital Goods",
    "JKCEMENT": "Construction Materials",
    "JKIL": "Construction",
    "JKLAKSHMI": "Construction Materials",
    "JKPAPER": "Forest Materials",
    "JKTYRE": "Automobile and Auto Components",
    "JMFINANCIL": "Financial Services",
    "JPPOWER": "Power",
    "JSFB": "Financial Services",
    "JSL": "Metals & Mining",
    "JSWENERGY": "Power",
    "JSWINFRA": "Services",
    "JSWSTEEL": "Metals & Mining",
    "JUBLFOOD": "Consumer Services",
    "JUBLINGREA": "Chemicals",
    "JUBLPHARMA": "Healthcare",
    "JUSTDIAL": "Consumer Services",
    "JWL": "Capital Goods",
    "JYOTHYLAB": "Fast Moving Consumer Goods",
    "JYOTICNC": "Capital Goods",
    "KAJARIACER": "Consumer Durables",
    "KALYANKJIL": "Consumer Durables",
    "KARURVYSYA": "Financial Services",
    "KAYNES": "Capital Goods",
    "KEC": "Construction",
    "KEI": "Capital Goods",
    "KFINTECH": "Financial Services",
    "KIMS": "Healthcare",
    "KIRLOSBROS": "Capital Goods",
    "KIRLOSENG": "Capital Goods",
    "KIRLPNU": "Capital Goods",
    "KITEX": "Textiles",
    "KNRCON": "Construction",
    "KOTAKBANK": "Financial Services",
    "KPIGREEN": "Power",
    "KPIL": "Construction",
    "KPITTECH": "Information Technology",
    "KPRMILL": "Textiles",
    "KRBL": "Fast Moving Consumer Goods",
    "KRN": "Capital Goods",
    "KSB": "Capital Goods",
    "KSCL": "Fast Moving Consumer Goods",
    "KSL": "Capital Goods",
    "KTKBANK": "Financial Services",
    "LALPATHLAB": "Healthcare",
    "LATENTVIEW": "Information Technology",
    "LAURUSLABS": "Healthcare",
    "LEMONTREE": "Consumer Services",
    "LICHSGFIN": "Financial Services",
    "LICI": "Financial Services",
    "LINDEINDIA": "Chemicals",
    "LLOYDSENGG": "Capital Goods",
    "LLOYDSENT": "Metals & Mining",
    "LLOYDSME": "Metals & Mining",
    "LMW": "Capital Goods",
    "LODHA": "Realty",
    "LT": "Construction",
    "LTF": "Financial Services",
    "LTFOODS": "Fast Moving Consumer Goods",
    "LTIM": "Information Technology",
    "LTTS": "Information Technology",
    "LUMAXTECH": "Automobile and Auto Components",
    "LUPIN": "Healthcare",
    "LUXIND": "Textiles",
    "LXCHEM": "Chemicals",
    "M&M": "Automobile and Auto Components",
    "M&MFIN": "Financial Services",
    "MAHABANK": "Financial Services",
    "MAHLIFE": "Realty",
    "MAHSCOOTER": "Financial Services",
    "MAHSEAMLES": "Capital Goods",
    "MANAPPURAM": "Financial Services",
    "MANINFRA": "Construction",
    "MANKIND": "Healthcare",
    "MANORAMA": "Fast Moving Consumer Goods",
    "MANYAVAR": "Consumer Services",
    "MAPMYINDIA": "Information Technology",
    "MARICO": "Fast Moving Consumer Goods",
    "MARKSANS": "Healthcare",
    "MARUTI": "Automobile and Auto Components",
    "MASTEK": "Information Technology",
    "MAXESTATES": "Realty",
    "MAXHEALTH": "Healthcare",
    "MAZDOCK": "Capital Goods",
    "MCX": "Financial Services",
    "MEDANTA": "Healthcare",
    "MEDPLUS": "Consumer Services",
    "METROPOLIS": "Healthcare",
    "MFSL": "Financial Services",
    "MGL": "Oil, Gas & Consumable Fuels",
    "MIDHANI": "Capital Goods",
    "MINDACORP": "Automobile and Auto Components",
    "MMTC": "Services",
    "MOIL": "Metals & Mining",
    "MOTHERSON": "Automobile and Auto Components",
    "MOTILALOFS": "Financial Services",
    "MPHASIS": "Information Technology",
    "MRF": "Automobile and Auto Components",
    "MRPL": "Oil, Gas & Consumable Fuels",
    "MSTCLTD": "Services",
    "MSUMI": "Automobile and Auto Components",
    "MTARTECH": "Capital Goods",
    "MUTHOOTFIN": "Financial Services",
    "NAM-INDIA": "Financial Services",
    "NATCOPHARM": "Healthcare",
    "NATIONALUM": "Metals & Mining",
    "NAUKRI": "Consumer Services",
    "NAVA": "Power",
    "NAVINFLUOR": "Chemicals",
    "NAZARA": "Media, Entertainment & Publication",
    "NBCC": "Construction",
    "NCC": "Construction",
    "NEOGEN": "Chemicals",
    "NESCO": "Services",
    "NESTLEIND": "Fast Moving Consumer Goods",
    "NETWEB": "Information Technology",
    "NETWORK18": "Media, Entertainment & Publication",
    "NEULANDLAB": "Healthcare",
    "NEWGEN": "Information Technology",
    "NFL": "Chemicals",
    "NH": "Healthcare",
    "NHPC": "Power",
    "NIACL": "Financial Services",
    "NIVABUPA": "Financial Services",
    "NLCINDIA": "Power",
    "NMDC": "Metals & Mining",
    "NSLNISP": "Metals & Mining",
    "NTPC": "Power",
    "NTPCGREEN": "Power",
    "NUVAMA": "Financial Services",
    "NUVOCO": "Construction Materials",
    "NYKAA": "Consumer Services",
    "OBEROIRLTY": "Realty",
    "OFSS": "Information Technology",
    "OIL": "Oil, Gas & Consumable Fuels",
    "OLAELEC": "Automobile and Auto Components",
    "OLECTRA": "Automobile and Auto Components",
    "ONESOURCE": "Healthcare",
    "ONGC": "Oil, Gas & Consumable Fuels",
    "OPTIEMUS": "Telecommunication",
    "ORCHPHARMA": "Healthcare",
    "ORIENTCEM": "Construction Materials",
    "OSWALPUMPS": "Capital Goods",
    "PAGEIND": "Textiles",
    "PARADEEP": "Chemicals",
    "PARAS": "Capital Goods",
    "PARKHOTELS": "Consumer Services",
    "PATANJALI": "Fast Moving Consumer Goods",
    "PATELENG": "Construction",
    "PAYTM": "Financial Services",
    "PCBL": "Chemicals",
    "PCJEWELLER": "Consumer Durables",
    "PERSISTENT": "Information Technology",
    "PETRONET": "Oil, Gas & Consumable Fuels",
    "PFC": "Financial Services",
    "PFIZER": "Healthcare",
    "PGEL": "Consumer Durables",
    "PGHH": "Fast Moving Consumer Goods",
    "PGIL": "Textiles",
    "PHOENIXLTD": "Realty",
    "PIDILITIND": "Chemicals",
    "PIIND": "Chemicals",
    "PNB": "Financial Services",
    "PNBHOUSING": "Financial Services",
    "PNCINFRA": "Construction",
    "PNGJL": "Consumer Durables",
    "POLICYBZR": "Financial Services",
    "POLYCAB": "Capital Goods",
    "POLYMED": "Healthcare",
    "POLYPLEX": "Capital Goods",
    "POONAWALLA": "Financial Services",
    "POWERGRID": "Power",
    "POWERINDIA": "Capital Goods",
    "POWERMECH": "Construction",
    "PPLPHARMA": "Healthcare",
    "PRAJIND": "Capital Goods",
    "PREMIERENE": "Capital Goods",
    "PRESTIGE": "Realty",
    "PRICOLLTD": "Automobile and Auto Components",
    "PRINCEPIPE": "Capital Goods",
    "PRIVISCL": "Chemicals",
    "PRSMJOHNSN": "Construction Materials",
    "PRUDENT": "Financial Services",
    "PTC": "Power",
    "PTCIL": "Capital Goods",
    "PURVA": "Realty",
    "PVRINOX": "Media, Entertainment & Publication",
    "QUESS": "Services",
    "RADICO": "Fast Moving Consumer Goods",
    "RAILTEL": "Telecommunication",
    "RAIN": "Chemicals",
    "RAINBOW": "Healthcare",
    "RAJESHEXPO": "Consumer Durables",
    "RALLIS": "Chemicals",
    "RAMCOCEM": "Construction Materials",
    "RATEGAIN": "Information Technology",
    "RATNAMANI": "Capital Goods",
    "RAYMONDLSL": "Textiles",
    "RBA": "Consumer Services",
    "RBLBANK": "Financial Services",
    "RCF": "Chemicals",
    "RECLTD": "Financial Services",
    "REDINGTON": "Services",
    "REFEX": "Chemicals",
    "RELAXO": "Consumer Durables",
    "RELIANCE": "Oil, Gas & Consumable Fuels",
    "RELIGARE": "Financial Services",
    "RELINFRA": "Power",
    "RENUKA": "Fast Moving Consumer Goods",
    "RHIM": "Capital Goods",
    "RITES": "Construction",
    "RKFORGE": "Automobile and Auto Components",
    "ROUTE": "Telecommunication",
    "RPOWER": "Power",
    "RRKABEL": "Capital Goods",
    "RTNINDIA": "Consumer Services",
    "RTNPOWER": "Power",
    "RVNL": "Construction",
    "SAFARI": "Consumer Durables",
    "SAGILITY": "Information Technology",
    "SAIL": "Metals & Mining",
    "SAILIFE": "Healthcare",
    "SAMHI": "Consumer Services",
    "SAMMAANCAP": "Financial Services",
    "SANDUMA": "Oil, Gas & Consumable Fuels",
    "SANOFI": "Healthcare",
    "SANOFICONR": "Healthcare",
    "SANSERA": "Automobile and Auto Components",
    "SAPPHIRE": "Consumer Services",
    "SARDAEN": "Metals & Mining",
    "SAREGAMA": "Media, Entertainment & Publication",
    "SBFC": "Financial Services",
    "SBICARD": "Financial Services",
    "SBILIFE": "Financial Services",
    "SBIN": "Financial Services",
    "SCHAEFFLER": "Automobile and Auto Components",
    "SCHNEIDER": "Capital Goods",
    "SCI": "Services",
    "SENCO": "Consumer Durables",
    "SFL": "Consumer Durables",
    "SHAILY": "Capital Goods",
    "SHAKTIPUMP": "Capital Goods",
    "SHARDACROP": "Chemicals",
    "SHARDAMOTR": "Automobile and Auto Components",
    "SHAREINDIA": "Financial Services",
    "SHILPAMED": "Healthcare",
    "SHREECEM": "Construction Materials",
    "SHRIPISTON": "Automobile and Auto Components",
    "SHRIRAMFIN": "Financial Services",
    "SHYAMMETL": "Capital Goods",
    "SIEMENS": "Capital Goods",
    "SIGNATURE": "Realty",
    "SJVN": "Power",
    "SKFINDIA": "Capital Goods",
    "SKIPPER": "Capital Goods",
    "SKYGOLD": "Consumer Durables",
    "SOBHA": "Realty",
    "SOLARINDS": "Chemicals",
    "SONACOMS": "Automobile and Auto Components",
    "SONATSOFTW": "Information Technology",
    "SOUTHBANK": "Financial Services",
    "SPARC": "Healthcare",
    "SRF": "Chemicals",
    "STAR": "Healthcare",
    "STARCEMENT": "Construction Materials",
    "STARHEALTH": "Financial Services",
    "STLTECH": "Telecommunication",
    "STYRENIX": "Chemicals",
    "SUBROS": "Capital Goods",
    "SUDARSCHEM": "Chemicals",
    "SUMICHEM": "Chemicals",
    "SUNDARMFIN": "Financial Services",
    "SUNDRMFAST": "Automobile and Auto Components",
    "SUNFLAG": "Capital Goods",
    "SUNPHARMA": "Healthcare",
    "SUNTECK": "Realty",
    "SUNTV": "Media, Entertainment & Publication",
    "SUPREMEIND": "Capital Goods",
    "SUPRIYA": "Healthcare",
    "SURYAROSNI": "Capital Goods",
    "SUZLON": "Capital Goods",
    "SWANCORP": "Chemicals",
    "SWIGGY": "Consumer Services",
    "SWSOLAR": "Construction",
    "SYMPHONY": "Consumer Durables",
    "SYNGENE": "Healthcare",
    "SYRMA": "Capital Goods",
    "TANLA": "Information Technology",
    "TARC": "Realty",
    "TARIL": "Capital Goods",
    "TATACHEM": "Chemicals",
    "TATACOMM": "Telecommunication",
    "TATACONSUM": "Fast Moving Consumer Goods",
    "TATAELXSI": "Information Technology",
    "TATAINVEST": "Financial Services",
    "TATAPOWER": "Power",
    "TATASTEEL": "Metals & Mining",
    "TATATECH": "Information Technology",
    "TBOTEK": "Consumer Services",
    "TCS": "Information Technology",
    "TDPOWERSYS": "Capital Goods",
    "TEAMLEASE": "Services",
    "TECHM": "Information Technology",
    "TECHNOE": "Construction",
    "TEGA": "Capital Goods",
    "TEJASNET": "Telecommunication",
    "TEXRAIL": "Capital Goods",
    "THANGAMAYL": "Consumer Durables",
    "THELEELA": "Consumer Services",
    "THERMAX": "Capital Goods",
    "THOMASCOOK": "Consumer Services",
    "THYROCARE": "Healthcare",
    "TI": "Fast Moving Consumer Goods",
    "TIINDIA": "Automobile and Auto Components",
    "TIMETECHNO": "Capital Goods",
    "TIMKEN": "Capital Goods",
    "TIPSMUSIC": "Media, Entertainment & Publication",
    "TITAGARH": "Capital Goods",
    "TITAN": "Consumer Durables",
    "TMCV": "Capital Goods",
    "TMPV": "Automobile and Auto Components",
    "TORNTPHARM": "Healthcare",
    "TORNTPOWER": "Power",
    "TRANSRAILL": "Capital Goods",
    "TRENT": "Consumer Services",
    "TRIDENT": "Textiles",
    "TRITURBINE": "Capital Goods",
    "TRIVENI": "Fast Moving Consumer Goods",
    "TSFINV": "Financial Services",
    "TTML": "Telecommunication",
    "TVSMOTOR": "Automobile and Auto Components",
    "TVSSCS": "Services",
    "UBL": "Fast Moving Consumer Goods",
    "UCOBANK": "Financial Services",
    "UJJIVANSFB": "Financial Services",
    "ULTRACEMCO": "Construction Materials",
    "UNIMECH": "Capital Goods",
    "UNIONBANK": "Financial Services",
    "UNITDSPR": "Fast Moving Consumer Goods",
    "UNOMINDA": "Automobile and Auto Components",
    "UPL": "Chemicals",
    "USHAMART": "Capital Goods",
    "UTIAMC": "Financial Services",
    "V2RETAIL": "Consumer Services",
    "VAIBHAVGBL": "Consumer Durables",
    "VARROC": "Automobile and Auto Components",
    "VBL": "Fast Moving Consumer Goods",
    "VEDL": "Metals & Mining",
    "VENTIVE": "Consumer Services",
    "VESUVIUS": "Capital Goods",
    "VGUARD": "Consumer Durables",
    "VIJAYA": "Healthcare",
    "VINATIORGA": "Chemicals",
    "VIPIND": "Consumer Durables",
    "VMART": "Consumer Services",
    "VMM": "Consumer Services",
    "VOLTAMP": "Capital Goods",
    "VOLTAS": "Consumer Durables",
    "VSTIND": "Fast Moving Consumer Goods",
    "VTL": "Textiles",
    "WAAREEENER": "Capital Goods",
    "WAAREERTL": "Capital Goods",
    "WABAG": "Utilities",
    "WEBELSOLAR": "Capital Goods",
    "WELCORP": "Capital Goods",
    "WELENT": "Construction",
    "WELSPUNLIV": "Textiles",
    "WESTLIFE": "Consumer Services",
    "WHIRLPOOL": "Consumer Durables",
    "WIPRO": "Information Technology",
    "WOCKPHARMA": "Healthcare",
    "YATHARTH": "Healthcare",
    "YESBANK": "Financial Services",
    "ZAGGLE": "Information Technology",
    "ZEEL": "Media, Entertainment & Publication",
    "ZENSARTECH": "Information Technology",
    "ZENTEC": "Capital Goods",
    "ZFCVINDIA": "Automobile and Auto Components",
    "ZYDUSLIFE": "Healthcare",
    "ZYDUSWELL": "Fast Moving Consumer Goods"
}

NUM_STOCKS_TO_COVER = 1
